{
    console.log('passo')
    console.log('passo')
    console.log('passo')
}
{
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
    console.log('passo')
     console.log('passo') 
}